# $schema: ../schema.json
name: $arrayToObject
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/arrayToObject/
type:
    - resolvesToObject
encode: array
description: |
    Converts an array of key value pairs to a document.
arguments:
    -
        name: array
        type:
            - resolvesToArray
tests:
    -
        name: $arrayToObject Example
        link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/arrayToObject/#-arraytoobject--example
        pipeline:
            -
                $project:
                    item: 1
                    dimensions:
                        $arrayToObject:
                            - $dimensions
        schema:
            inventory:
                _id:
                    types:
                        -
                            bsonType: Number
                item:
                    types:
                        -
                            bsonType: String
                dimensions:
                    types:
                        -
                            bsonType: Array
                            types:
                                -
                                    bsonType: Array
                                    types:
                                        -
                                            bsonType: String
                                        -
                                            bsonType: Number
                                -
                                    bsonType: Document
                                    fields:
                                        k:
                                            types:
                                                -
                                                    bsonType: String
                                        v:
                                            types:
                                                -
                                                    bsonType: Number
                                                -
                                                    bsonType: String
    -
        name: $objectToArray and $arrayToObject Example
        link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/arrayToObject/#-objecttoarray----arraytoobject-example
        pipeline:
            -
                $addFields:
                    instock:
                        $objectToArray: $instock
            -
                $addFields:
                    instock:
                        $concatArrays:
                            - $instock
                            -
                                -
                                    k: total
                                    v:
                                        $sum:
                                            - $instock.v
            -
                $addFields:
                    instock:
                        $arrayToObject:
                            - $instock
        schema:
            inventory:
                _id:
                    types:
                        -
                            bsonType: Number
                item:
                    types:
                        -
                            bsonType: String
                instock:
                    types:
                        -
                            bsonType: Document
                            fields:
                                warehouse1:
                                    types:
                                        -
                                            bsonType: Number
                                warehouse2:
                                    types:
                                        -
                                            bsonType: Number
                                warehouse3:
                                    types:
                                        -
                                            bsonType: Number
