# $schema: ../schema.json
name: $atan2
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/atan2/'
type:
    - resolvesToDouble
    - resolvesToDecimal
encode: array
description: |
    Returns the inverse tangent (arc tangent) of y / x in radians, where y and x are the first and second values passed to the expression respectively.
arguments:
    -
        name: 'y'
        type:
            - resolvesToNumber
        description: |
            $atan2 takes any valid expression that resolves to a number.
            $atan2 returns values in radians. Use $radiansToDegrees operator to convert the output value from radians to degrees.
            By default $atan returns values as a double. $atan2 can also return values as a 128-bit decimal as long as the expression resolves to a 128-bit decimal value.
    -
        name: x
        type:
            - resolvesToNumber
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/atan2/#example'
        pipeline:
            -
                $addFields:
                    angle_a:
                        $radiansToDegrees:
                            $atan2:
                                - '$side_b'
                                - '$side_a'
