# $schema: ../schema.json
name: $concat
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/concat/'
type:
    - resolvesToString
encode: single
description: |
    Concatenates any number of strings.
arguments:
    -
        name: expression
        type:
            - resolvesToString
        variadic: array
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/concat/#examples'
        pipeline:
            -
                $project:
                    itemDescription:
                        $concat:
                            - '$item'
                            - ' - '
                            - '$description'
