# $schema: ../schema.json
name: $concat
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/concat/
type:
    - resolvesToString
encode: single
description: |
    Concatenates any number of strings.
arguments:
    - name: expression
      type:
          - resolvesToString
      variadic: array
tests:
    - name: Example
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/concat/#example
      pipeline:
          - $project:
                itemDescription:
                    $concat:
                        - $item
                        - ' - '
                        - $description
      schema:
          inventory:
              _id:
                  types:
                      - bsonType: Number
              item:
                  types:
                      - bsonType: String
              quarter:
                  types:
                      - bsonType: String
              description:
                  types:
                      - bsonType: String
                      - bsonType: 'Null'
