# $schema: ../schema.json
name: $convert
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/convert/'
type:
    - resolvesToAny
encode: object
description: |
    Converts a value to a specified type.
    New in MongoDB 4.0.
arguments:
    -
        name: input
        type:
            - expression
    -
        name: to
        type:
            - resolvesToString
            - resolvesToInt
    -
        name: onError
        type:
            - expression
        optional: true
        description: |
            The value to return on encountering an error during conversion, including unsupported type conversions. The arguments can be any valid expression.
            If unspecified, the operation throws an error upon encountering an error and stops.
    -
        name: onNull
        type:
            - expression
        optional: true
        description: |
            The value to return if the input is null or missing. The arguments can be any valid expression.
            If unspecified, $convert returns null if the input is null or missing.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/convert/#example'
        pipeline:
            -
                $addFields:
                    convertedPrice:
                        $convert:
                            input: '$price'
                            to: 'decimal'
                            onError: 'Error'
                            onNull: !bson_decimal128 '0'
                    convertedQty:
                        $convert:
                            input: '$qty'
                            to: 'int'
                            onError:
                                $concat:
                                    - 'Could not convert '
                                    -
                                        $toString: '$qty'
                                    - ' to type integer.'
                            onNull: 0
            -
                $project:
                    totalPrice:
                        $switch:
                            branches:
                                -
                                    case:
                                        $eq:
                                            -
                                                $type: '$convertedPrice'
                                            - 'string'
                                    then: 'NaN'
                                -
                                    case:
                                        $eq:
                                            -
                                                $type: '$convertedQty'
                                            - 'string'
                                    then: 'NaN'
                            default:
                                $multiply:
                                    - '$convertedPrice'
                                    - '$convertedQty'
