# $schema: ../schema.json
name: $dateAdd
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/dateAdd/'
type:
    - resolvesToDate
encode: object
description: |
    Adds a number of time units to a date object.
arguments:
    -
        name: startDate
        type:
            - resolvesToDate
            - resolvesToTimestamp
            - resolvesToObjectId
        description: |
            The beginning date, in UTC, for the addition operation. The startDate can be any expression that resolves to a Date, a Timestamp, or an ObjectID.
    -
        name: unit
        type:
            - timeUnit
        description: |
            The unit used to measure the amount of time added to the startDate.
    -
        name: amount
        type:
            - resolvesToInt
            - resolvesToLong
    -
        name: timezone
        type:
            - resolvesToString
        optional: true
        description: |
            The timezone to carry out the operation. $timezone must be a valid expression that resolves to a string formatted as either an Olson Timezone Identifier or a UTC Offset. If no timezone is provided, the result is displayed in UTC.
tests:
    -
        name: 'Add a Future Date'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/dateAdd/#add-a-future-date'
        pipeline:
            -
                $project:
                    expectedDeliveryDate:
                        $dateAdd:
                            startDate: '$purchaseDate'
                            unit: 'day'
                            amount: 3
            -
                # Example uses the short form, the builder always generates the verbose form
                # $merge: 'shipping'
                $merge:
                    into: 'shipping'
    -
        name: 'Filter on a Date Range'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/dateAdd/#filter-on-a-date-range'
        pipeline:
            -
                $match:
                    $expr:
                        $gt:
                            - '$deliveryDate'
                            -
                                $dateAdd:
                                    startDate: '$purchaseDate'
                                    unit: 'day'
                                    amount: 5
            -
                $project:
                    _id: 0
                    custId: 1
                    purchased:
                        $dateToString:
                            format: '%Y-%m-%d'
                            date: '$purchaseDate'
                    delivery:
                        $dateToString:
                            format: '%Y-%m-%d'
                            date: '$deliveryDate'
    -
        name: 'Adjust for Daylight Savings Time'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/dateAdd/#adjust-for-daylight-savings-time'
        pipeline:
            -
                $project:
                    _id: 0
                    location: 1
                    start:
                        $dateToString:
                            format: '%Y-%m-%d %H:%M'
                            date: '$login'
                    days:
                        $dateToString:
                            format: '%Y-%m-%d %H:%M'
                            date:
                                $dateAdd:
                                    startDate: '$login'
                                    unit: 'day'
                                    amount: 1
                                    timezone: '$location'
                    hours:
                        $dateToString:
                            format: '%Y-%m-%d %H:%M'
                            date:
                                $dateAdd:
                                    startDate: '$login'
                                    unit: 'hour'
                                    amount: 24
                                    timezone: '$location'
                    startTZInfo:
                        $dateToString:
                            format: '%Y-%m-%d %H:%M'
                            date: '$login'
                            timezone: '$location'
                    daysTZInfo:
                        $dateToString:
                            format: '%Y-%m-%d %H:%M'
                            date:
                                $dateAdd:
                                    startDate: '$login'
                                    unit: 'day'
                                    amount: 1
                                    timezone: '$location'
                            timezone: '$location'
                    hoursTZInfo:
                        $dateToString:
                            format: '%Y-%m-%d %H:%M'
                            date:
                                $dateAdd:
                                    startDate: '$login'
                                    unit: 'hour'
                                    amount: 24
                                    timezone: '$location'
                            timezone: '$location'
