# $schema: ../schema.json
name: $ln
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/ln/'
type:
    - resolvesToDouble
encode: single
description: |
    Calculates the natural log of a number. 
    $ln is equivalent to $log: [ <number>, Math.E ] expression, where Math.E is a JavaScript representation for Euler's number e.
arguments:
    -
        name: number
        type:
            - resolvesToNumber
        description: |
            Any valid expression as long as it resolves to a non-negative number. For more information on expressions, see Expressions.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/ln/#example'
        pipeline:
            -
                $project:
                    x: '$year'
                    y:
                        $ln: '$sales'
