# $schema: ../schema.json
name: $median
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/median/'
type:
    - resolvesToDouble
encode: object
description: |
    Returns an approximation of the median, the 50th percentile, as a scalar value.
    New in MongoDB 7.0.
    This operator is available as an accumulator in these stages:
    $group
    $setWindowFields
    It is also available as an aggregation expression.
arguments:
    -
        name: input
        type:
            - resolvesToNumber
        description: |
            $median calculates the 50th percentile value of this data. input must be a field name or an expression that evaluates to a numeric type. If the expression cannot be converted to a numeric type, the $median calculation ignores it.
    -
        name: method
        type:
            - string # AccumulatorPercentile
        description: |
            The method that mongod uses to calculate the 50th percentile value. The method must be 'approximate'.
