# $schema: ../schema.json
name: $replaceAll
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceAll/'
type:
    - resolvesToString
encode: object
description: |
    Replaces all instances of a search string in an input string with a replacement string.
    $replaceAll is both case-sensitive and diacritic-sensitive, and ignores any collation present on a collection.
    New in MongoDB 4.4.
arguments:
    -
        name: input
        type:
            - resolvesToString
            - resolvesToNull
        description: |
            The string on which you wish to apply the find. Can be any valid expression that resolves to a string or a null. If input refers to a field that is missing, $replaceAll returns null.
    -
        name: find
        type:
            - resolvesToString
            - resolvesToNull
        description: |
            The string to search for within the given input. Can be any valid expression that resolves to a string or a null. If find refers to a field that is missing, $replaceAll returns null.
    -
        name: replacement
        type:
            - resolvesToString
            - resolvesToNull
        description: |
            The string to use to replace all matched instances of find in input. Can be any valid expression that resolves to a string or a null.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceAll/#example'
        pipeline:
            -
                $project:
                    item:
                        $replaceAll:
                            input: '$item'
                            find: 'blue paint'
                            replacement: 'red paint'
