# $schema: ../schema.json
name: $toInt
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/toInt/
type:
    - resolvesToInt
encode: single
description: |
    Converts value to an integer.
    New in MongoDB 4.0.
arguments:
    - name: expression
      type:
          - expression
tests:
    - name: Example
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/toInt/#example
      pipeline:
          - $addFields:
                convertedQty:
                    $toInt: $qty
      schema:
          orders:
              _id:
                  types:
                      - bsonType: Number
              item:
                  types:
                      - bsonType: String
              qty:
                  types:
                      - bsonType: String
              price:
                  types:
                      - bsonType: Number
                      - bsonType: Decimal128
                      - bsonType: String
