# $schema: ../schema.json
name: $type
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/type/
type:
    - resolvesToString
encode: single
description: |
    Return the BSON data type of the field.
arguments:
    - name: expression
      type:
          - expression
tests:
    - name: Example
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/type/#example
      pipeline:
          - $project:
                a:
                    $type: $a
      schema:
          TestCollection:
              _id:
                  types:
                      - bsonType: Number
              a:
                  types:
                      - bsonType: Number
                      - bsonType: Array
                        types:
                            - bsonType: Number
                      - bsonType: Document
                        fields:
                            a:
                                types:
                                    - bsonType: String
                            b:
                                types:
                                    - bsonType: String
                            c:
                                types:
                                    - bsonType: String
                      - bsonType: String
                      - bsonType: Long
