version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "v1.21"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gitsubmodule"
    target-branch: "v1.21"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*drivers-evergreen-tools"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*specifications"
