name: Setup
description: Sets up the build environment
inputs:
  php-version:
    description: "PHP version to install"
    required: true
  driver-version:
    description: "MongoDB extension version to install"
    required: true
  php-ini-values:
    description: "INI values to pass along to setup-php action"
    required: false
    default: ""
  working-directory:
    description: "The directory where composer.json is located, if it is not in the repository root."
    required: false

runs:
  using: composite
  steps:
    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@de3c642a5fce0ef91581a1c9831e229f525196d6  # 1.15.1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: "mongodb-${{ inputs.driver-version }}"
        key: "extcache-${{ inputs.driver-version }}"

    - name: Cache extensions
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Install PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # 2.37.2
      with:
        coverage: none
        extensions: "mongodb-${{ inputs.driver-version }}"
        php-version: "${{ inputs.php-version }}"
        tools: cs2pr
        ini-values: "${{ inputs.php-ini-values }}"

    - name: Show driver information
      run: "php --ri mongodb"
      shell: bash

    - name: Install dependencies with Composer
      uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda  # 4.0.0
      with:
        composer-options: "--no-suggest"
        working-directory: "${{ inputs.working-directory }}"
