  # Variants with different PHPC versions
  - name: test-debian12-php-%phpVersion%-phpc-next-stable
    tags: ["test", "debian", "x64", "php%phpVersion%", "pr", "tag"]
    display_name: "Test: Debian 12, PHP %phpVersion%, PHPC next-stable"
    run_on: debian12-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian12"
      FETCH_BUILD_TASK: "build-php-%phpVersion%-next-stable"
      PHP_VERSION: "%phpVersion%"
    depends_on:
      - variant: "build-debian12"
        name: "build-php-%phpVersion%-next-stable"
    tasks:
      - ".standalone .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".replicaset .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".sharded .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".loadbalanced .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - "test_serverless_task_group"
      - "test_serverless_proxy_task_group"
      - "test-atlas-data-lake"

  - name: test-debian12-php-%phpVersion%-phpc-next-minor
    tags: ["test", "debian", "x64", "php%phpVersion%"]
    display_name: "Test: Debian 12, PHP %phpVersion%, PHPC next-minor"
    run_on: debian12-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian12"
      FETCH_BUILD_TASK: "build-php-%phpVersion%-next-minor"
      PHP_VERSION: "%phpVersion%"
    depends_on:
      - variant: "build-debian12"
        name: "build-php-%phpVersion%-next-minor"
    tasks:
      - ".standalone .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".replicaset .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".sharded .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".loadbalanced .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - "test_serverless_task_group"
      - "test_serverless_proxy_task_group"
      - "test-atlas-data-lake"
