# $schema: ../schema.json
name: $planCacheStats
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/planCacheStats/
type:
    - stage
encode: object
description: |
    Returns plan cache information for a collection.
tests:
    - name: Return Information for All Entries in the Query Cache
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/planCacheStats/#return-information-for-all-entries-in-the-query-cache
      pipeline:
          - $planCacheStats: {}
      schema:
          orders:
              _id:
                  types:
                      - bsonType: Number
              item:
                  types:
                      - bsonType: String
              price:
                  types:
                      - bsonType: Decimal128
              quantity:
                  types:
                      - bsonType: Number
              type:
                  types:
                      - bsonType: String
    - name: Find Cache Entry Details for a Query Hash
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/planCacheStats/#find-cache-entry-details-for-a-query-hash
      pipeline:
          - $planCacheStats: {}
          - $match:
                planCacheKey: B1435201
      schema:
          orders:
              _id:
                  types:
                      - bsonType: Number
              item:
                  types:
                      - bsonType: String
              price:
                  types:
                      - bsonType: Decimal128
              quantity:
                  types:
                      - bsonType: Number
              type:
                  types:
                      - bsonType: String
