# $schema: ../schema.json
name: $replaceRoot
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceRoot/
type:
    - stage
encode: object
description: |
    Replaces a document with the specified embedded document. The operation replaces all existing fields in the input document, including the _id field. Specify a document embedded in the input document to promote the embedded document to the top level.
arguments:
    - name: newRoot
      type:
          - resolvesToObject
tests:
    - name: with an Embedded Document Field
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceRoot/#-replaceroot-with-an-embedded-document-field
      pipeline:
          - $replaceRoot:
                newRoot:
                    $mergeObjects:
                        - dogs: 0
                          cats: 0
                          birds: 0
                          fish: 0
                        - $pets
      schema:
          TestCollection:
              _id:
                  types:
                      - bsonType: Number
              name:
                  types:
                      - bsonType: String
              age:
                  types:
                      - bsonType: Number
              pets:
                  types:
                      - bsonType: Document
                        fields:
                            dogs:
                                types:
                                    - bsonType: Number
                            cats:
                                types:
                                    - bsonType: Number
                            fish:
                                types:
                                    - bsonType: Number
    - name: with a Document Nested in an Array
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceRoot/#-replaceroot-with-a-document-nested-in-an-array
      pipeline:
          - $unwind:
                path: $grades
          - $match:
                grades.grade:
                    $gte: 90
          - $replaceRoot:
                newRoot: $grades
      schema:
          students:
              _id:
                  types:
                      - bsonType: Number
              grades:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: Document
                              fields:
                                  test:
                                      types:
                                          - bsonType: Number
                                  grade:
                                      types:
                                          - bsonType: Number
                                  mean:
                                      types:
                                          - bsonType: Number
                                  std:
                                      types:
                                          - bsonType: Number
    - name: with a newly created document
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceRoot/#-replaceroot-with-a-newly-created-document
      pipeline:
          - $replaceRoot:
                newRoot:
                    full_name:
                        $concat:
                            - $first_name
                            - ' '
                            - $last_name
      schema:
          TestCollection:
              _id:
                  types:
                      - bsonType: Number
              first_name:
                  types:
                      - bsonType: String
              last_name:
                  types:
                      - bsonType: String
              city:
                  types:
                      - bsonType: String
    - name: with a New Document Created from $$ROOT and a Default Document
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceRoot/#-replaceroot-with-a-new-document-created-from---root-and-a-default-document
      pipeline:
          - $replaceRoot:
                newRoot:
                    $mergeObjects:
                        - _id: ''
                          name: ''
                          email: ''
                          cell: ''
                          home: ''
                        - $$ROOT
      schema:
          contacts:
              _id:
                  types:
                      - bsonType: Number
              name:
                  types:
                      - bsonType: String
              email:
                  types:
                      - bsonType: String
              cell:
                  types:
                      - bsonType: String
              home:
                  types:
                      - bsonType: String
