# $schema: ../schema.json
name: $sortByCount
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/sortByCount/
type:
    - stage
encode: single
description: |
    Groups incoming documents based on the value of a specified expression, then computes the count of documents in each distinct group.
arguments:
    - name: expression
      type:
          - expression
tests:
    - name: Example
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/sortByCount/#examples
      pipeline:
          - $unwind:
                path: $tags
          - $sortByCount: $tags
      schema:
          exhibits:
              _id:
                  types:
                      - bsonType: Number
              title:
                  types:
                      - bsonType: String
              artist:
                  types:
                      - bsonType: String
              year:
                  types:
                      - bsonType: Number
              tags:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
