# $schema: ../schema.json
name: $unset
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/unset/
type:
    - stage
encode: single
description: |
    Removes or excludes fields from documents.
    Alias for $project stage that removes or excludes fields.
arguments:
    - name: field
      type:
          - unprefixedFieldPath
      variadic: array
tests:
    - name: Remove a Single Field
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/unset/#remove-a-single-field
      pipeline:
          - $unset:
                - copies
      schema:
          books:
              _id:
                  types:
                      - bsonType: Number
              title:
                  types:
                      - bsonType: String
              isbn:
                  types:
                      - bsonType: String
              author:
                  types:
                      - bsonType: Document
                        fields:
                            last:
                                types:
                                    - bsonType: String
                            first:
                                types:
                                    - bsonType: String
              copies:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: Document
                              fields:
                                  warehouse:
                                      types:
                                          - bsonType: String
                                  qty:
                                      types:
                                          - bsonType: Number
    - name: Remove Top-Level Fields
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/unset/#remove-top-level-fields
      pipeline:
          - $unset:
                - isbn
                - copies
      schema:
          books:
              _id:
                  types:
                      - bsonType: Number
              title:
                  types:
                      - bsonType: String
              isbn:
                  types:
                      - bsonType: String
              author:
                  types:
                      - bsonType: Document
                        fields:
                            last:
                                types:
                                    - bsonType: String
                            first:
                                types:
                                    - bsonType: String
              copies:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: Document
                              fields:
                                  warehouse:
                                      types:
                                          - bsonType: String
                                  qty:
                                      types:
                                          - bsonType: Number
    - name: Remove Embedded Fields
      link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/unset/#remove-embedded-fields
      pipeline:
          - $unset:
                - isbn
                - author.first
                - copies.warehouse
      schema:
          books:
              _id:
                  types:
                      - bsonType: Number
              title:
                  types:
                      - bsonType: String
              isbn:
                  types:
                      - bsonType: String
              author:
                  types:
                      - bsonType: Document
                        fields:
                            last:
                                types:
                                    - bsonType: String
                            first:
                                types:
                                    - bsonType: String
              copies:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: Document
                              fields:
                                  warehouse:
                                      types:
                                          - bsonType: String
                                  qty:
                                      types:
                                          - bsonType: Number
