# $schema: ../schema.json
name: $exists
link: https://www.mongodb.com/docs/manual/reference/operator/query/exists/
type:
    - fieldQuery
encode: single
description: |
    Matches documents that have the specified field.
arguments:
    - name: exists
      type:
          - bool
      default: true
tests:
    - name: Exists and Not Equal To
      link: https://www.mongodb.com/docs/manual/reference/operator/query/exists/#exists-and-not-equal-to
      pipeline:
          - $match:
                qty:
                    $exists: true
                    $nin:
                        - 5
                        - 15
      schema:
          inventory: &ref_0
              price:
                  types:
                      - bsonType: Double
              qty:
                  types:
                      - bsonType: Int32
                      - bsonType: Undefined
              sale:
                  types:
                      - bsonType: Boolean
    - name: Null Values
      link: https://www.mongodb.com/docs/manual/reference/operator/query/exists/#null-values
      pipeline:
          - $match:
                qty:
                    $exists: true
      schema:
          inventory: *ref_0
