# $schema: ../schema.json
name: $jsonSchema
link: https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/
type:
    - query
encode: single
description: |
    Validate documents against the given JSON Schema.
arguments:
    - name: schema
      type:
          - object
tests:
    - name: Example
      link: https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#syntax
      pipeline:
          - $match:
                $jsonSchema:
                    required:
                        - name
                        - major
                        - gpa
                        - address
                    properties:
                        name:
                            bsonType: string
                            description: must be a string and is required
                        address:
                            bsonType: object
                            required:
                                - zipcode
                            properties:
                                street:
                                    bsonType: string
                                zipcode:
                                    bsonType: string
      schema:
          TestCollection:
              name:
                  types:
                      - bsonType: String
              major:
                  types:
                      - bsonType: String
              gpa:
                  types:
                      - bsonType: Double
              address:
                  types:
                      - bsonType: Document
                        fields:
                            street:
                                types:
                                    - bsonType: String
                            zipcode:
                                types:
                                    - bsonType: String
