# $schema: ../schema.json
name: $ne
link: https://www.mongodb.com/docs/manual/reference/operator/query/ne/
type:
    - fieldQuery
encode: single
description: |
    Matches all values that are not equal to a specified value.
arguments:
    - name: value
      type:
          - any
tests:
    - name: Match Document Fields
      link: https://www.mongodb.com/docs/manual/reference/operator/query/ne/#match-document-fields-that-are-not-equal
      pipeline:
          - $match:
                quantity:
                    $ne: 20
      schema:
          inventory:
              item:
                  types:
                      - bsonType: String
              quantity:
                  types:
                      - bsonType: Number
              carrier:
                  types:
                      - bsonType: Document
                        fields:
                            name:
                                types:
                                    - bsonType: String
                            fee:
                                types:
                                    - bsonType: Number
