# $schema: ../schema.json
name: $type
link: https://www.mongodb.com/docs/manual/reference/operator/query/type/
type:
    - fieldQuery
encode: single
description: |
    Selects documents if a field is of the specified type.
arguments:
    - name: type
      type:
          - int
          - string
      variadic: array
tests:
    - name: Querying by Data Type
      link: https://www.mongodb.com/docs/manual/reference/operator/query/type/#querying-by-data-type
      pipeline:
          - $match:
                zipCode:
                    $type:
                        - 2
          - $match:
                zipCode:
                    $type:
                        - string
          - $match:
                zipCode:
                    $type:
                        - 1
          - $match:
                zipCode:
                    $type:
                        - double
          - $match:
                zipCode:
                    $type:
                        - number
      schema:
          addressBook:
              _id:
                  types:
                      - bsonType: Number
              address:
                  types:
                      - bsonType: String
              zipCode:
                  types:
                      - bsonType: String
                      - bsonType: Number
                      - bsonType: Long
                      - bsonType: Int32
                      - bsonType: Array
                        types:
                            - bsonType: String
    - name: Querying by Multiple Data Type
      link: https://www.mongodb.com/docs/manual/reference/operator/query/type/#querying-by-multiple-data-types
      pipeline:
          - $match:
                zipCode:
                    $type:
                        - 2
                        - 1
          - $match:
                zipCode:
                    $type:
                        - string
                        - double
      schema:
          grades:
              _id:
                  types:
                      - bsonType: Number
              name:
                  types:
                      - bsonType: String
              classAverage:
                  types:
                      - bsonType: String
                      - bsonType: Number
                      - bsonType: Int32
    - name: Querying by MinKey and MaxKey
      link: https://www.mongodb.com/docs/manual/reference/operator/query/type/#querying-by-minkey-and-maxkey
      pipeline:
          - $match:
                zipCode:
                    $type:
                        - minKey
          - $match:
                zipCode:
                    $type:
                        - maxKey
      schema:
          addressBook:
              _id:
                  types:
                      - bsonType: Number
              address:
                  types:
                      - bsonType: String
              zipCode:
                  types:
                      - bsonType: String
                      - bsonType: Number
                      - bsonType: Long
                      - bsonType: Int32
                      - bsonType: Array
                        types:
                            - bsonType: String
    - name: Querying by Array Type
      link: https://www.mongodb.com/docs/manual/reference/operator/query/type/#querying-by-array-type
      pipeline:
          - $match:
                zipCode:
                    $type:
                        - array
      schema:
          sensorReading:
              _id:
                  types:
                      - bsonType: Number
              readings:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: Number
                            - bsonType: Array
                              types:
                                  - bsonType: String
                                  - bsonType: Number
                      - bsonType: Number
