# $schema: ../schema.json
name: facet
link: https://www.mongodb.com/docs/atlas/atlas-search/facet/
type:
    - searchOperator
encode: object
description: |
    The facet collector groups results by values or ranges in the specified
    faceted fields and returns the count for each of those groups.
arguments:
    - name: facets
      type:
          - object
    - name: operator
      optional: true
      type:
          - searchOperator
tests:
    - name: Facet
      link: https://www.mongodb.com/docs/atlas/atlas-search/facet/#examples
      pipeline:
          - $search:
                facet:
                    operator:
                        near:
                            path: released
                            origin: !bson_utcdatetime '1999-07-01T00:00:00.000Z'
                            pivot: 7776000000
                    facets:
                        genresFacet:
                            type: string
                            path: genres
          - $limit: 2
          - $facet:
                docs:
                    - $project:
                          title: 1
                          released: 1
                meta:
                    - $replaceWith: $$SEARCH_META
                    - $limit: 1
          - $set:
                meta:
                    $arrayElemAt:
                        - $meta
                        - 0
      schema:
          movies:
              _id:
                  types:
                      - bsonType: Document
                        fields:
                            $oid:
                                types:
                                    - bsonType: String
              title:
                  types:
                      - bsonType: String
              year:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              runtime:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              released:
                  types:
                      - bsonType: Document
                        fields:
                            $date:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberLong:
                                              types:
                                                  - bsonType: String
              poster:
                  types:
                      - bsonType: String
              plot:
                  types:
                      - bsonType: String
              fullplot:
                  types:
                      - bsonType: String
              lastupdated:
                  types:
                      - bsonType: String
              type:
                  types:
                      - bsonType: String
              directors:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              imdb:
                  types:
                      - bsonType: Document
                        fields:
                            rating:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberDouble:
                                              types:
                                                  - bsonType: String
                            votes:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
                            id:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
              cast:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              countries:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              genres:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              tomatoes:
                  types:
                      - bsonType: Document
                        fields:
                            viewer:
                                types:
                                    - bsonType: Document
                                      fields:
                                          rating:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberDouble:
                                                            types:
                                                                - bsonType: String
                                          numReviews:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberInt:
                                                            types:
                                                                - bsonType: String
                            lastUpdated:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $date:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberLong:
                                                            types:
                                                                - bsonType: String
              num_mflix_comments:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
