# $schema: ../schema.json
name: in
link: https://www.mongodb.com/docs/atlas/atlas-search/in/
type:
    - searchOperator
encode: object
description: |
    The in operator performs a search for an array of BSON values in a field.
arguments:
    -
        name: path
        type:
            - searchPath
    -
        name: value
        type:
            - any
            - array
    -
        name: score
        optional: true
        type:
            - searchScore
tests:
    -
        name: Single Value Field Match
        link: https://www.mongodb.com/docs/atlas/atlas-search/in/#examples
        pipeline:
            -
                $search:
                    in:
                        path: birthdate
                        value:
                            - 1977-03-02T02:20:31.000Z
                            - 1977-03-01T00:00:00.000Z
                            - 1977-05-06T21:57:35.000Z
            -
                $project:
                    _id: 0
                    name: 1
                    birthdate: 1
    -
        name: Array Value Field Match
        link: https://www.mongodb.com/docs/atlas/atlas-search/in/#examples
        pipeline:
            -
                $search:
                    in:
                        path: accounts
                        value:
                            - 371138
                            - 371139
                            - 371140
            -
                $project:
                    _id: 0
                    name: 1
                    accounts: 1
    -
        name: Compound Query Match
        link: https://www.mongodb.com/docs/atlas/atlas-search/in/#examples
        pipeline:
            -
                $search:
                    compound:
                        must:
                            -
                                in:
                                    path: name
                                    value:
                                        - james sanchez
                                        - jennifer lawrence
                        should:
                            -
                                in:
                                    path: _id
                                    value:
                                        -
                                            buffer: !!binary XKS7zqLdlO5YFipy
                                        -
                                            buffer: !!binary XKS7zqLdlO5YFiqR
            -
                $limit: 5
            -
                $project:
                    _id: 1
                    name: 1
                    score:
                        $meta: searchScore
