# $schema: ../schema.json
name: phrase
link: https://www.mongodb.com/docs/atlas/atlas-search/phrase/
type:
    - searchOperator
encode: object
description: |
    The phrase operator performs search for documents containing an ordered sequence of terms using the analyzer specified in the index configuration.
arguments:
    - name: path
      type:
          - searchPath
    - name: query
      type:
          - string
          - array
    - name: slop
      optional: true
      type:
          - int
    - name: synonyms
      optional: true
      type:
          - string
    - name: score
      optional: true
      type:
          - searchScore
tests:
    - name: Single Phrase
      link: https://www.mongodb.com/docs/atlas/atlas-search/phrase/#single-phrase-example
      pipeline:
          - $search:
                phrase:
                    path: title
                    query: new york
          - $limit: 10
          - $project:
                _id: 0
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: &ref_0
              _id:
                  types:
                      - bsonType: Document
                        fields:
                            $oid:
                                types:
                                    - bsonType: String
              title:
                  types:
                      - bsonType: String
              year:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              runtime:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              released:
                  types:
                      - bsonType: Document
                        fields:
                            $date:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberLong:
                                              types:
                                                  - bsonType: String
              poster:
                  types:
                      - bsonType: String
              plot:
                  types:
                      - bsonType: String
              fullplot:
                  types:
                      - bsonType: String
              lastupdated:
                  types:
                      - bsonType: String
              type:
                  types:
                      - bsonType: String
              directors:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              imdb:
                  types:
                      - bsonType: Document
                        fields:
                            rating:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberDouble:
                                              types:
                                                  - bsonType: String
                            votes:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
                            id:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
              cast:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              countries:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              genres:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              tomatoes:
                  types:
                      - bsonType: Document
                        fields:
                            viewer:
                                types:
                                    - bsonType: Document
                                      fields:
                                          rating:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberDouble:
                                                            types:
                                                                - bsonType: String
                                          numReviews:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberInt:
                                                            types:
                                                                - bsonType: String
                            lastUpdated:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $date:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberLong:
                                                            types:
                                                                - bsonType: String
              num_mflix_comments:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
    - name: Multiple Phrase
      link: https://www.mongodb.com/docs/atlas/atlas-search/phrase/#multiple-phrases-example
      pipeline:
          - $search:
                phrase:
                    path: title
                    query:
                        - the man
                        - the moon
          - $limit: 10
          - $project:
                _id: 0
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
    - name: Phrase Slop
      link: https://www.mongodb.com/docs/atlas/atlas-search/phrase/#slop-example
      pipeline:
          - $search:
                phrase:
                    path: title
                    query: men women
                    slop: 5
          - $project:
                _id: 0
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
    - name: Phrase Synonyms
      link: https://www.mongodb.com/docs/atlas/atlas-search/phrase/#synonyms-example
      pipeline:
          - $search:
                phrase:
                    path: plot
                    query: automobile race
                    slop: 5
                    synonyms: my_synonyms
          - $limit: 5
          - $project:
                _id: 0
                plot: 1
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
