# $schema: ../schema.json
name: regex
link: https://www.mongodb.com/docs/atlas/atlas-search/regex/
type:
    - searchOperator
encode: object
description: |
    regex interprets the query field as a regular expression.
    regex is a term-level operator, meaning that the query field isn't analyzed.
arguments:
    - name: path
      type:
          - searchPath
    - name: query
      type:
          - string
    - name: allowAnalyzedField
      optional: true
      type:
          - bool
    - name: score
      optional: true
      type:
          - searchScore
tests:
    - name: Regex
      link: https://www.mongodb.com/docs/atlas/atlas-search/regex/#examples
      pipeline:
          - $search:
                regex:
                    path: title
                    query: '[0-9]{2} (.){4}s'
          - $project:
                _id: 0
                title: 1
      schema:
          movies:
              _id:
                  types:
                      - bsonType: Document
                        fields:
                            $oid:
                                types:
                                    - bsonType: String
              title:
                  types:
                      - bsonType: String
              year:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              runtime:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              released:
                  types:
                      - bsonType: Document
                        fields:
                            $date:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberLong:
                                              types:
                                                  - bsonType: String
              poster:
                  types:
                      - bsonType: String
              plot:
                  types:
                      - bsonType: String
              fullplot:
                  types:
                      - bsonType: String
              lastupdated:
                  types:
                      - bsonType: String
              type:
                  types:
                      - bsonType: String
              directors:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              imdb:
                  types:
                      - bsonType: Document
                        fields:
                            rating:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberDouble:
                                              types:
                                                  - bsonType: String
                            votes:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
                            id:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
              cast:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              countries:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              genres:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              tomatoes:
                  types:
                      - bsonType: Document
                        fields:
                            viewer:
                                types:
                                    - bsonType: Document
                                      fields:
                                          rating:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberDouble:
                                                            types:
                                                                - bsonType: String
                                          numReviews:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberInt:
                                                            types:
                                                                - bsonType: String
                            lastUpdated:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $date:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberLong:
                                                            types:
                                                                - bsonType: String
              num_mflix_comments:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
