# $schema: ../schema.json
name: text
link: https://www.mongodb.com/docs/atlas/atlas-search/text/
type:
    - searchOperator
encode: object
description: |
    The text operator performs a full-text search using the analyzer that you specify in the index configuration.
    If you omit an analyzer, the text operator uses the default standard analyzer.
arguments:
    - name: path
      type:
          - searchPath
    - name: query
      type:
          - string
    - name: fuzzy
      optional: true
      type:
          - object
    - name: matchCriteria
      optional: true
      type:
          - string
    - name: synonyms
      optional: true
      type:
          - string
    - name: score
      optional: true
      type:
          - searchScore
tests:
    - name: Basic
      link: https://www.mongodb.com/docs/atlas/atlas-search/text/#basic-example
      pipeline:
          - $search:
                text:
                    path: title
                    query: surfer
          - $project:
                _id: 0
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: &ref_0
              _id:
                  types:
                      - bsonType: Document
                        fields:
                            $oid:
                                types:
                                    - bsonType: String
              title:
                  types:
                      - bsonType: String
              year:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              runtime:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              released:
                  types:
                      - bsonType: Document
                        fields:
                            $date:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberLong:
                                              types:
                                                  - bsonType: String
              poster:
                  types:
                      - bsonType: String
              plot:
                  types:
                      - bsonType: String
              fullplot:
                  types:
                      - bsonType: String
              lastupdated:
                  types:
                      - bsonType: String
              type:
                  types:
                      - bsonType: String
              directors:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              imdb:
                  types:
                      - bsonType: Document
                        fields:
                            rating:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberDouble:
                                              types:
                                                  - bsonType: String
                            votes:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
                            id:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
              cast:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              countries:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              genres:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              tomatoes:
                  types:
                      - bsonType: Document
                        fields:
                            viewer:
                                types:
                                    - bsonType: Document
                                      fields:
                                          rating:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberDouble:
                                                            types:
                                                                - bsonType: String
                                          numReviews:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberInt:
                                                            types:
                                                                - bsonType: String
                            lastUpdated:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $date:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberLong:
                                                            types:
                                                                - bsonType: String
              num_mflix_comments:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
    - name: Fuzzy Default
      link: https://www.mongodb.com/docs/atlas/atlas-search/text/#fuzzy-examples
      pipeline:
          - $search:
                text:
                    path: title
                    query: naw yark
                    fuzzy: {}
          - $limit: 10
          - $project:
                _id: 0
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
    - name: Fuzzy maxExpansions
      link: https://www.mongodb.com/docs/atlas/atlas-search/text/#fuzzy-examples
      pipeline:
          - $search:
                text:
                    path: title
                    query: naw yark
                    fuzzy:
                        maxEdits: 1
                        maxExpansions: 100
          - $limit: 10
          - $project:
                _id: 0
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
    - name: Fuzzy prefixLength
      link: https://www.mongodb.com/docs/atlas/atlas-search/text/#fuzzy-examples
      pipeline:
          - $search:
                text:
                    path: title
                    query: naw yark
                    fuzzy:
                        maxEdits: 1
                        prefixLength: 2
          - $limit: 8
          - $project:
                _id: 1
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
    - name: Match any Using equivalent Mapping
      link: https://www.mongodb.com/docs/atlas/atlas-search/text/#match-any-using-equivalent-mapping
      pipeline:
          - $search:
                text:
                    path: plot
                    query: attire
                    synonyms: my_synonyms
                    matchCriteria: any
          - $limit: 5
          - $project:
                _id: 0
                plot: 1
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
    - name: Match any Using explicit Mapping
      link: https://www.mongodb.com/docs/atlas/atlas-search/text/#match-any-using-explicit-mapping
      pipeline:
          - $search:
                text:
                    path: plot
                    query: boat race
                    synonyms: my_synonyms
                    matchCriteria: any
          - $limit: 10
          - $project:
                _id: 0
                plot: 1
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
    - name: Match all Using Synonyms
      link: https://www.mongodb.com/docs/atlas/atlas-search/text/#match-all-using-synonyms
      pipeline:
          - $search:
                text:
                    path: plot
                    query: automobile race
                    matchCriteria: all
                    synonyms: my_synonyms
          - $limit: 20
          - $project:
                _id: 0
                plot: 1
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
    - name: Wildcard Path
      link: https://www.mongodb.com/docs/atlas/atlas-search/text/
      pipeline:
          - $search:
                text:
                    path:
                        wildcard: '*'
                    query: surfer
          - $project:
                _id: 0
                title: 1
                score:
                    $meta: searchScore
      schema:
          movies: *ref_0
