# $schema: ../schema.json
name: wildcard
link: https://www.mongodb.com/docs/atlas/atlas-search/wildcard/
type:
    - searchOperator
encode: object
description: |
    The wildcard operator enables queries which use special characters in the search string that can match any character.
arguments:
    - name: path
      type:
          - searchPath
    - name: query
      type:
          - string
    - name: allowAnalyzedField
      optional: true
      type:
          - bool
    - name: score
      optional: true
      type:
          - searchScore
tests:
    - name: Wildcard Path
      link: https://www.mongodb.com/docs/atlas/atlas-search/wildcard/#index-definition
      pipeline:
          - $search:
                wildcard:
                    query: Wom?n *
                    path:
                        wildcard: '*'
          - $limit: 5
          - $project:
                _id: 0
                title: 1
      schema:
          movies: &ref_0
              _id:
                  types:
                      - bsonType: Document
                        fields:
                            $oid:
                                types:
                                    - bsonType: String
              title:
                  types:
                      - bsonType: String
              year:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              runtime:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
              released:
                  types:
                      - bsonType: Document
                        fields:
                            $date:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberLong:
                                              types:
                                                  - bsonType: String
              poster:
                  types:
                      - bsonType: String
              plot:
                  types:
                      - bsonType: String
              fullplot:
                  types:
                      - bsonType: String
              lastupdated:
                  types:
                      - bsonType: String
              type:
                  types:
                      - bsonType: String
              directors:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              imdb:
                  types:
                      - bsonType: Document
                        fields:
                            rating:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberDouble:
                                              types:
                                                  - bsonType: String
                            votes:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
                            id:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $numberInt:
                                              types:
                                                  - bsonType: String
              cast:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              countries:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              genres:
                  types:
                      - bsonType: Array
                        types:
                            - bsonType: String
              tomatoes:
                  types:
                      - bsonType: Document
                        fields:
                            viewer:
                                types:
                                    - bsonType: Document
                                      fields:
                                          rating:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberDouble:
                                                            types:
                                                                - bsonType: String
                                          numReviews:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberInt:
                                                            types:
                                                                - bsonType: String
                            lastUpdated:
                                types:
                                    - bsonType: Document
                                      fields:
                                          $date:
                                              types:
                                                  - bsonType: Document
                                                    fields:
                                                        $numberLong:
                                                            types:
                                                                - bsonType: String
              num_mflix_comments:
                  types:
                      - bsonType: Document
                        fields:
                            $numberInt:
                                types:
                                    - bsonType: String
    - name: Escape Character Example
      link: https://www.mongodb.com/docs/atlas/atlas-search/wildcard/#escape-character-example
      pipeline:
          - $search:
                wildcard:
                    query: '*\?'
                    path: title
          - $limit: 5
          - $project:
                _id: 0
                title: 1
      schema:
          movies: *ref_0
