name: Merge up

on:
  push:
    branches:
      - "v[0-9]+.[0-9x]+"

jobs:
  merge-up:
    name: Create merge up pull request
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Create app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          submodules: true
          fetch-depth: 0

      - name: Create pull request
        id: create-pull-request
        uses: alcaeus/automatic-merge-up-action@1.1.0
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          ref: ${{ github.ref_name }}
          branchNamePattern: 'v<major>.<minor>'
          devBranchNamePattern: 'v<major>.x'
          ignoredBranches: ${{ vars.IGNORED_MERGE_UP_BRANCHES }}
          labels: merge-up
          enableAutoMerge: true
          assignApprover: true
