name: "Submodule Validation"

on:
  merge_group:
    paths:
      - ".gitmodules"
      - ".github/workflows/submodules.yml"
      - "tests/drivers-evergreen-tools"
      - "tests/specifications"
      - "generator/mql-specifications"
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
    paths:
      - ".gitmodules"
      - ".github/workflows/submodules.yml"
      - "tests/drivers-evergreen-tools"
      - "tests/specifications"
      - "generator/mql-specifications"

jobs:
  validate-submodules:
    name: "Validate submodule references"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Validate submodule commits"
        uses: "mongodb-labs/drivers-github-tools/validate-submodules@main"
        with:
          token: ${{ github.token }}
