name: "Submodule Validation"

on:
  merge_group:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"

jobs:
  validate-submodules:
    name: "Validate submodule references"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Validate submodule commits"
        uses: "mongodb-labs/drivers-github-tools/validate-submodules@v3"
        with:
          token: ${{ github.token }}
